### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by benioriginal** [italoseara/whatsappy#15]
Successfully logged in
Traceback (most recent call last):
  File "c:\Users\BeniN\one = 1 copy 2.py", line 6, in <module>
    whatsapp.chat(name="Fara diriga Idk")
  File "C:\Users\BeniN\AppData\Roaming\Python\Python310\site-packages\whatsappy\main.py", line 159, in chat
    self.Group(self, name) 
  File "C:\Users\BeniN\AppData\Roaming\Python\Python310\site-packages\whatsappy\main.py", line 569, in __init__
    self._driver.find_elements(By.CSS_SELECTOR, "div[data-testid=cell-frame-container]")[1].click()
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 
321, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document

also whatsapp.chat works with groups too? and when i promote someone whatsapp.Group.promote(contacts="name") or what?

**Comment by italoseara** [comment]
This library hasn't been updated in a while, whatsapp web has updated a lot since then, as the library works by clicking in html elements, it could have changed, im planning to update it very soon, and as soon as it happens, i'll make sure this will be fixed.

**Comment by benioriginal** [comment]
Okay, thanks! :D
